#!/bin/bash
set -e
case "$(basename "${EXECUTABLE:?EXECUTABLE missing}")" in
puzzles)
  export OXIDE_PRELOAD_FORCE_INVERT_TOUCH_X=1
  export OXIDE_PRELOAD_FORCE_32BIT_FSCREEN=1
  ;;
tilem | yaft)
  export OXIDE_PRELOAD_FORCE_RM1=1
  ;;
chessmarkable | doommarkable)
  if [[ "$(cat /sys/devices/soc0/machine)" != "reMarkable 2.0" ]]; then
    export OXIDE_PRELOAD_FORCE_RM1=1
  fi
  export OXIDE_PRELOAD_FORCE_32BIT_FSCREEN=1
  ;;
esac
eval "set -- $ARGUMENTS"
exec /home/root/.vellum/bin/blight-client "$EXECUTABLE" "$@"
