/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p wpa_supplicant.h:wpa_supplicant.cpp fi.w1.wpa_supplicant1.xml
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "wpa_supplicant.h"

/*
 * Implementation of interface class FiW1Wpa_supplicant1Interface
 */

FiW1Wpa_supplicant1Interface::FiW1Wpa_supplicant1Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

FiW1Wpa_supplicant1Interface::~FiW1Wpa_supplicant1Interface()
{
}

/*
 * Implementation of interface class FiW1Wpa_supplicant1BSSInterface
 */

FiW1Wpa_supplicant1BSSInterface::FiW1Wpa_supplicant1BSSInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

FiW1Wpa_supplicant1BSSInterface::~FiW1Wpa_supplicant1BSSInterface()
{
}

/*
 * Implementation of interface class FiW1Wpa_supplicant1InterfaceInterface
 */

FiW1Wpa_supplicant1InterfaceInterface::FiW1Wpa_supplicant1InterfaceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

FiW1Wpa_supplicant1InterfaceInterface::~FiW1Wpa_supplicant1InterfaceInterface()
{
}

/*
 * Implementation of interface class FiW1Wpa_supplicant1NetworkInterface
 */

FiW1Wpa_supplicant1NetworkInterface::FiW1Wpa_supplicant1NetworkInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

FiW1Wpa_supplicant1NetworkInterface::~FiW1Wpa_supplicant1NetworkInterface()
{
}

