#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(erode fret oxide rot tarnish decay corrupt anxiety mold)
pkgver="2.2-~VERSION~"
timestamp="$(date -u +%Y-%m-%dT%H:%MZ)"
maintainer="Eeems <eeems@eeems.email>"
license=MIT
source=(oxide.tar.gz)
sha256sums=(SKIP)

erode() {
    pkgdesc="Task manager"
    url=https://github.com/Eeems/oxide/tree/master/applications/process-manager
    section=utils
    depends=("tarnish (= $pkgver)")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/opt/bin/erode
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/opt/usr/share/applications/codes.eeems.erode.oxide
    }
}

fret() {
    pkgdesc="Take screenshots"
    url=https://github.com/Eeems/oxide/tree/master/applications/screenshot-tool
    section=utils
    depends=("tarnish (= $pkgver)")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/opt/bin/fret
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/opt/usr/share/applications/codes.eeems.fret.oxide
    }
}

oxide() {
    pkgdesc="Launcher application"
    url=https://github.com/Eeems/oxide/tree/master/applications/launcher
    section=launchers
    depends=("erode  (= $pkgver)" "fret (= $pkgver)" "tarnish (= $pkgver)" "rot (= $pkgver)" "decay (= $pkgver)" "corrupt (= $pkgver)")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/opt/bin/oxide
        install -D -m 644 -t "$pkgdir"/opt/etc "$srcdir"/opt/etc/oxide.conf
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/opt/usr/share/applications/codes.eeems.oxide.oxide
    }

    configure() {
        if ! is-enabled "tarnish.service"; then
            echo ""
            echo "Run the following command(s) to use $pkgname as your launcher"
            how-to-enable "tarnish.service"
            echo ""
        fi
    }
}

rot() {
    pkgdesc="Manage Oxide settings through the command line"
    url=https://github.com/Eeems/oxide/tree/master/applications/settings-manager
    section=utils
    depends=("tarnish (= $pkgver)")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/opt/bin/rot
    }
}

tarnish() {
    pkgdesc="Service managing power states, connectivity and buttons"
    url=https://github.com/Eeems/oxide/tree/master/applications/system-service
    section=utils

    package() {
        install -D -m 644 -t "$pkgdir"/etc/dbus-1/system.d "$srcdir"/etc/dbus-1/system.d/codes.eeems.oxide.conf
        install -D -m 644 -t "$pkgdir"/lib/systemd/system "$srcdir"/etc/systemd/system/tarnish.service
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/opt/bin/tarnish
    }

    configure() {
        systemctl daemon-reload
    }

    preremove() {
        if systemctl list-units --full -all | grep -Fq 'tarnish.service'; then
            echo "Disabling $pkgname"
            systemctl disable --now tarnish
        fi
    }

    postremove() {
        systemctl daemon-reload
    }
}

decay() {
    pkgdesc="Lockscreen application"
    url=https://github.com/Eeems/oxide/tree/master/applications/lockscreen
    section=utils
    depends=("tarnish (= $pkgver)")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/opt/bin/decay
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/opt/usr/share/applications/codes.eeems.decay.oxide
    }
}

corrupt() {
    pkgdesc="Task Switcher for Oxide"
    url=https://github.com/Eeems/oxide/tree/master/applications/task-switcher
    section=utils
    depends=("tarnish (= $pkgver)")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/opt/bin/corrupt
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/opt/usr/share/applications/codes.eeems.corrupt.oxide
    }
}

anxiety() {
    pkgdesc="Screenshot viewer for Oxide"
    url=https://github.com/Eeems/oxide/tree/master/applications/screenshot-viewer
    section=utils
    depends=("tarnish (= $pkgver)")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/opt/bin/anxiety
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/opt/usr/share/applications/codes.eeems.anxiety.oxide
        install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/opt/etc/draft/icons/image.svg
    }
}

mold() {
    pkgdesc="Web Browser for Oxide"
    url=https://github.com/Eeems/oxide/tree/master/applications/web-browser
    section=utils
    depends=("tarnish (= $pkgver)")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/opt/bin/mold
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/opt/usr/share/applications/codes.eeems.mold.oxide
        install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/opt/etc/draft/icons/web.svg
    }
}
