#!/usr/bin/env bash
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(erode fret oxide rot tarnish decay corrupt anxiety liboxide libsentry notify-send update-desktop-database)
pkgver="2.6~VERSION~"
timestamp="$(date -u +%Y-%m-%dT%H:%MZ)"
maintainer="Eeems <eeems@eeems.email>"
url=https://oxide.eeems.codes
license=MIT
source=(oxide.tar.gz)
sha256sums=(SKIP)
image=qt:latest
_sentry=0.5.0

build() {
    find . -name "*.pro" -type f -print0 \
        | xargs -r -0 sed -i 's/linux-oe-g++/linux-arm-remarkable-g++/g'
    CMAKE_TOOLCHAIN_FILE="/usr/share/cmake/$CHOST.cmake" make FEATURES=sentry release
    # Cleanup build files
    rm -r .build
}

erode() {
    pkgdesc="Task manager"
    section=utils
    installdepends=("tarnish=$pkgver" "liboxide=$pkgver" "libsentry=$_sentry")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/erode
        install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/release/opt/etc/draft/icons/erode.svg
        install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/release/opt/etc/draft/icons/erode-splash.png
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/release/opt/usr/share/applications/codes.eeems.erode.oxide
    }
}

fret() {
    pkgdesc="Take screenshots"
    section=utils
    installdepends=("tarnish=$pkgver" "liboxide=$pkgver"  "libsentry=$_sentry")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/fret
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/release/opt/usr/share/applications/codes.eeems.fret.oxide
    }
}

oxide() {
    pkgdesc="Launcher application"
    section=launchers
    installdepends=("erode=$pkgver" "fret=$pkgver" "tarnish=$pkgver" "rot=$pkgver" "decay=$pkgver" "corrupt=$pkgver" "liboxide=$pkgver" "update-desktop-database=$pkgver" display  "libsentry=$_sentry")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/oxide
        install -D -m 644 -t "$pkgdir"/opt/etc "$srcdir"/release/opt/etc/oxide.conf
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/release/opt/usr/share/applications/codes.eeems.oxide.oxide
        install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/release/opt/etc/draft/icons/oxide-splash.png
    }

    configure() {
        if ! is-enabled "tarnish.service"; then
            echo ""
            echo "Run the following command(s) to use $pkgname as your launcher"
            how-to-enable "tarnish.service"
            echo ""
        fi
    }
}

rot() {
    pkgdesc="Manage Oxide settings through the command line"
    section=utils
    installdepends=("tarnish=$pkgver" "liboxide=$pkgver" "libsentry=$_sentry")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/rot
    }
}

tarnish() {
    pkgdesc="Service managing power states, connectivity and buttons"
    section=utils
    installdepends=("liboxide=$pkgver" "libsentry=$_sentry")

    package() {
        install -D -m 644 -t "$pkgdir"/etc/dbus-1/system.d "$srcdir"/release/etc/dbus-1/system.d/codes.eeems.oxide.conf
        install -D -m 644 -t "$pkgdir"/lib/systemd/system "$srcdir"/release/etc/systemd/system/tarnish.service
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/tarnish
    }

    configure() {
        systemctl daemon-reload
    }

    preremove() {
        if systemctl list-units --full -all | grep -Fq 'tarnish.service'; then
            echo "Disabling $pkgname"
            systemctl disable --now tarnish
        fi
    }

    postremove() {
        systemctl daemon-reload
    }
}

decay() {
    pkgdesc="Lockscreen application"
    section=utils
    installdepends=("tarnish=$pkgver" "liboxide=$pkgver" "libsentry=$_sentry")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/decay
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/release/opt/usr/share/applications/codes.eeems.decay.oxide
    }
}

corrupt() {
    pkgdesc="Task Switcher for Oxide"
    section=utils
    installdepends=("tarnish=$pkgver" "liboxide=$pkgver" "libsentry=$_sentry")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/corrupt
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/release/opt/usr/share/applications/codes.eeems.corrupt.oxide
    }
}

anxiety() {
    pkgdesc="Screenshot viewer for Oxide"
    section=utils
    installdepends=("tarnish=$pkgver" "liboxide=$pkgver" "libsentry=$_sentry")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/anxiety
        install -D -m 644 -t "$pkgdir"/opt/usr/share/applications "$srcdir"/release/opt/usr/share/applications/codes.eeems.anxiety.oxide
        install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/release/opt/etc/draft/icons/image.svg
        install -D -m 644 -t "$pkgdir"/opt/etc/draft/icons "$srcdir"/release/opt/etc/draft/icons/anxiety-splash.png
    }
}

notify-send() {
    pkgdesc="A program to send desktop notifications for Oxide"
    section=utils
    installdepends=("tarnish=$pkgver" "liboxide=$pkgver" "libsentry=$_sentry")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/notify-send
    }
}
update-desktop-database(){
    pkgdesc="A program to update the application cache for Oxide"
    section=utils
    installdepends=("tarnish=$pkgver" "liboxide=$pkgver" "libsentry=$_sentry")

    package() {
        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/release/opt/bin/update-desktop-database
    }
}

liboxide() {
    pkgdesc="Shared library for oxide applications"
    section=devel

    package() {
        install -D -m 755 -t "$pkgdir"/opt/usr/lib "$srcdir"/release/opt/usr/lib/libliboxide.so*
    }
}

libsentry() {
    pkgdesc="Sentry SDK for C, C++ and native applications."
    section=devel
    url=https://github.com/getsentry/sentry-native
    pkgver="$_sentry"
    timestamp="2021-12-20T14:25:11Z"

    package() {
        install -D -m 755 -t "$pkgdir"/opt/lib "$srcdir"/release/opt/lib/libsentry.so
    }
}
