#!/bin/bash
if [ "${1}" == "pre" ]; then
  QDBUS_DEBUG=1 /opt/bin/rot apps call suspended &> /tmp/suspend.log
elif [ "${1}" == "post" ]; then
  QDBUS_DEBUG=1 /opt/bin/rot apps call resumed &>> /tmp/suspend.log
fi;
