#if defined __cplusplus
#include <cstring>
#include <fstream>
#include <functional>
#include <linux/input.h>
#include <QCoreApplication>
#include <QCryptographicHash>
#include <QDBusAbstractInterface>
#include <QDBusArgument>
#include <QDBusConnection>
#include <QDBusError>
#include <QDBusServiceWatcher>
#include <QDebug>
#include <QDir>
#include <QEvent>
#include <QFile>
#include <QFileSystemWatcher>
#include <QGuiApplication>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonValue>
#include <QLibraryInfo>
#include <QList>
#include <QMetaMethod>
#include <QMetaProperty>
#include <QMouseEvent>
#include <QObject>
#include <QQuickItem>
#include <QScopeGuard>
#include <QScreen>
#include <QSettings>
#include <QSocketNotifier>
#include <QString>
#include <QTabletEvent>
#include <QTextStream>
#include <QtGlobal>
#include <QThread>
#include <QTimer>
#include <QUuid>
#include <QVariant>
#include <signal.h>
#include <sstream>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <sys/socket.h>
#include <sys/un.h>
#include <systemd/sd-id128.h>
#include <unistd.h>

#include "liboxide_global.h"
#include "meta.h"
#endif
