#if defined __cplusplus
#include <grp.h>
#include <linux/input.h>
#include <pwd.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <sys/un.h>
#include <systemd/sd-id128.h>
#include <unistd.h>

#include <QCoreApplication>
#include <QCryptographicHash>
#include <QDBusAbstractInterface>
#include <QDBusArgument>
#include <QDBusConnection>
#include <QDBusError>
#include <QDBusServiceWatcher>
#include <QDebug>
#include <QDir>
#include <QEvent>
#include <QFile>
#include <QFileSystemWatcher>
#include <QGuiApplication>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonValue>
#include <QLibraryInfo>
#include <QList>
#include <QMetaMethod>
#include <QMetaProperty>
#include <QMouseEvent>
#include <QObject>
#include <QQuickItem>
#include <QScopeGuard>
#include <QScreen>
#include <QSettings>
#include <QSocketNotifier>
#include <QString>
#include <QTabletEvent>
#include <QTextStream>
#include <QThread>
#include <QTimer>
#include <QUuid>
#include <QVariant>
#include <QtGlobal>
#include <cstring>
#include <fstream>
#include <functional>
#include <sstream>
#include <string>

#include "application_interface.h"
#include "appsapi_interface.h"
#include "bss_interface.h"
#include "dbusservice_interface.h"
#include "liboxide_global.h"
#include "meta.h"
#include "network_interface.h"
#include "notification_interface.h"
#include "notificationapi_interface.h"
#include "powerapi_interface.h"
#include "systemapi_interface.h"
#include "wifiapi_interface.h"
#endif
