#if defined __cplusplus
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <liboxide.h>
#include <linux/fb.h>
#include <memory>
#include <QAbstractListModel>
#include <QDebug>
#include <QDir>
#include <QFile>
#include <QGuiApplication>
#include <QIODevice>
#include <QJsonObject>
#include <QMap>
#include <QMutableListIterator>
#include <QObject>
#include <QProcess>
#include <QQmlApplicationEngine>
#include <QQuickItem>
#include <QSet>
#include <QSettings>
#include <QStandardPaths>
#include <QStringList>
#include <QtDBus>
#include <QTextStream>
#include <QTimer>
#include <QtPlugin>
#include <QtQuick>
#include <signal.h>
#include <sstream>
#include <stdlib.h>
#include <sys/mman.h>
#include <unistd.h>

#include "application_interface.h"
#include "appsapi_interface.h"
#include "bss_interface.h"
#include "dbusservice_interface.h"
#include "network_interface.h"
#include "notification_interface.h"
#include "notificationapi_interface.h"
#include "powerapi_interface.h"
#include "systemapi_interface.h"
#include "wifiapi_interface.h"

#include "controller.h"
#include "mxcfb.h"
#endif
