#!/bin/bash
set -e
case "$1" in
is-active)
	pid=$(systemctl show --property MainPID --value xochitl.service)
	if [ "$pid" -eq 0 ]; then
		exit 1
	fi
	! cat /proc/"$pid"/environ | tr '\0' '\n' | grep LD_PRELOAD | grep -q xovi.so
	;;
is-enabled | enable | disable | paused)
	;;
logs)
	if [ $# -eq 2 ] && [[ "$2" == "-f" ]] || [[ "$2" == "--follow" ]]; then
		journalctl --follow --all --unit xochitl.service
	else
		journalctl --no-pager --all --unit xochitl.service
	fi
	;;
start | launch)
	systemctl start xochitl.service
	;;
stop | close)
	systemctl stop xochitl.service
	;;
apps)
	echo "xochitl"
	;;
running)
	if "$0" is-active; then
		echo "xochitl"
	fi
	;;
*)
	echo "Xochitl does not support this method"
	exit 1
	;;
esac
