#!/bin/bash
set -e
log() {
  printf "%s lockscreen_hook\t%s\n" "$(date --utc '+%H:%M:%S')" "$1" 1>&2
}
launcher="$(/home/root/.vellum/bin/launcherctl current-launcher)"
log "Starting $launcher"
if ! /home/root/.vellum/bin/launcherctl start-launcher --no-stop; then
  log "Failed to start launcher, running xochitl instead"
  exec /usr/bin/xochitl
fi
log "$launcher started"
