VERSION = 3.0

DEFINES += QT_DEPRECATED_WARNINGS
DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x051510

QMAKE_RPATHDIR += /lib /usr/lib /opt/lib /opt/usr/lib
DEFINES += APP_VERSION=\\\"$$VERSION\\\"

CONFIG += c++17
CONFIG += c++18
CONFIG += c++19
