name: Build doxygen docs
description: Build doxygen docs
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"
    - name: Cache Python environment
      uses: actions/cache@v4
      id: cache-python
      with:
        path: web/.venv
        key: web/.venv-${{ hashFiles('web/requirements.txt') }}
    - name: Apt-Cache-Action
      uses: Eeems-Org/apt-cache-action@v1
      with:
        packages: texlive-base texlive-latex-extra doxygen graphviz libgraphviz-dev librsvg2-bin pdf2svg qhelpgenerator-qt5
    - name: Build website
      shell: bash
      run: cd web && make prod
    - name: Generate libblight_protocol docs
      shell: bash
      run: |
        cd shared/libblight_protocol && make prod
    - name: Generate libblight docs
      shell: bash
      run: |
        cd shared/libblight && make prod
    - name: Generate liboxide docs
      shell: bash
      run: |
        cd shared/liboxide && make prod
