name: Build doxygen docs
description: Build doxygen docs
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Cache Python environment
      uses: actions/cache@v3
      id: cache-python
      with:
        path: web/.venv
        key: web/.venv-${{ hashFiles('web/requirements.txt') }}
    - name: Install base Apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: doxygen graphviz libgraphviz-dev
        version: 1.0
    - name: Cache Images
      uses: actions/cache@v3
      id: cache-images
      with:
        key: images-${{ hashFiles('images/*.tex') }}
        path: |
          src/_static/images/*.png
          src/_static/images/*.svg
    - name: Install texlive Apt packages
      if: ${{ !steps.cache-images.outputs.cache-hit }}
      shell: bash
      run: |
        sudo apt-get update -yq && sudo apt-get install -yq --no-install-recommends librsvg2-bin texlive-full pdf2svg
    - name: Build website
      shell: bash
      run: cd web && make prod
    - name: Generate liboxide docs
      shell: bash
      run: |
        cd shared/liboxide && make prod
