name: Build oxide

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build.yml"
      - "applications/**"
      - "shared/**"
      - "assets/**"
      - "interfaces/**"
      - "qmake/**"
      - "oxide.pro"
      - "Makefile"
      - "package"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "applications/**"
      - "shared/**"
      - "assets/**"
      - "interfaces/**"
      - "qmake/**"
      - "oxide.pro"
      - "Makefile"
      - "package"
permissions:
  contents: read
jobs:
  lint:
    name: Lint source
    runs-on: ubuntu-latest
    steps:
      - name: Cache shfmt
        uses: actions/cache@v5
        with:
          path: /usr/local/bin/shfmt
          key: 43439b996942b53dfafa9b6ff084f394555d049c98fb7ec37978f7668b43e1be
      - name: Install shfmt
        shell: bash
        run: |
          install_dir=/usr/local/bin
          if ! [[ -f "$install_dir"/shfmt ]]; then
              shfmt_version=v3.2.1
              shfmt_checksum=43439b996942b53dfafa9b6ff084f394555d049c98fb7ec37978f7668b43e1be
              sudo curl --location --silent --fail --tlsv1.2 --proto '=https' \
                  --output "$install_dir"/shfmt \
                  https://github.com/mvdan/sh/releases/download/"$shfmt_version"/shfmt_"$shfmt_version"_linux_amd64
              sha256sum -c <(echo "$shfmt_checksum $install_dir/shfmt") > /dev/null 2>&1
              sudo chmod a+x "$install_dir"/shfmt
          fi
      - name: Install clang-format
        shell: bash
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22 clang-format-22
          sudo apt-get install -y clang-format-22
          sudo ln -sf clang-format-22 /usr/bin/clang-format
          clang-format --version
      - uses: actions/checkout@v6
      - name: Lint
        run: make lint
  build:
    name: Build and package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - armv7
          - aarch64
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install vbuild
        run: |
          curl \
            --location \
            "https://github.com/Eeems/vbuild/releases/latest/download/vbuild-x86_64-glibc" \
            --output /usr/local/bin/vbuild
          chmod +x /usr/local/bin/vbuild
          file /usr/local/bin/vbuild
      - name: Install vbuild key
        run: |
          mkdir -p $HOME/.config/vbuild
          cd $HOME/.config/vbuild
          echo '$privkey' > oxide.rsa
          chmod 600 oxide.rsa
          openssl rsa -in oxide.rsa -pubout -out oxide.rsa.pub
        env:
          privkey: ${{ secrets.VBUILD_PRIVKEY }}
      - name: Build packages
        run: make package-${{ matrix.arch }}
        env:
          VBUILD_KEY_NAME: oxide
        timeout-minutes: 15
      - name: Save packages
        uses: actions/upload-artifact@v7
        with:
          name: vellum-${{ matrix.arch }}
          path: release/${{ matrix.arch }}/
      - name: Save build
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ matrix.arch }}
          path: .build/package/src/release/
          include-hidden-files: true
