name: Build oxide

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build.yml"
      - "applications/**"
      - "shared/**"
      - "assets/**"
      - "interfaces/**"
      - "qmake/**"
      - "oxide.pro"
      - "Makefile"
      - "package"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "applications/**"
      - "shared/**"
      - "assets/**"
      - "interfaces/**"
      - "qmake/**"
      - "oxide.pro"
      - "Makefile"
      - "package"
permissions:
  contents: read
jobs:
  lint:
    name: Lint source
    runs-on: ubuntu-latest
    steps:
      - name: Cache shfmt
        uses: actions/cache@v5
        with:
          path: /usr/local/bin/shfmt
          key: 43439b996942b53dfafa9b6ff084f394555d049c98fb7ec37978f7668b43e1be
      - name: Install shfmt
        shell: bash
        run: |
          install_dir=/usr/local/bin
          if ! [[ -f "$install_dir"/shfmt ]]; then
              shfmt_version=v3.2.1
              shfmt_checksum=43439b996942b53dfafa9b6ff084f394555d049c98fb7ec37978f7668b43e1be
              sudo curl --location --silent --fail --tlsv1.2 --proto '=https' \
                  --output "$install_dir"/shfmt \
                  https://github.com/mvdan/sh/releases/download/"$shfmt_version"/shfmt_"$shfmt_version"_linux_amd64
              sha256sum -c <(echo "$shfmt_checksum $install_dir/shfmt") > /dev/null 2>&1
              sudo chmod a+x "$install_dir"/shfmt
          fi
      - name: Install clang-format
        shell: bash
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22 clang-format-22
          sudo apt-get install -y clang-format-22
          sudo ln -sf clang-format-22 /usr/bin/clang-format
          clang-format --version
      - uses: actions/checkout@v6
      - name: Lint
        run: make lint
  build:
    name: Build and package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - armv7
          - aarch64
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install vbuild
        run: |
          curl \
            --location \
            "https://github.com/Eeems/vbuild/releases/latest/download/vbuild-x86_64-glibc" \
            --output /usr/local/bin/vbuild
          chmod +x /usr/local/bin/vbuild
          file /usr/local/bin/vbuild
      - name: Install vbuild key
        run: |
          mkdir -p $HOME/.config/vbuild
          cd $HOME/.config/vbuild
          echo "$privkey" > oxide.rsa
          chmod 600 oxide.rsa
          openssl rsa -in oxide.rsa -pubout -out oxide.rsa.pub
          if ! diff -w <(cat oxide.rsa.pub) <(echo "$pubkey");then
            echo "::error::Public and Private keys don't match!"
            exit 1
          fi
        env:
          privkey: ${{ secrets.VBUILD_PRIVKEY }}
          pubkey: ${{ vars.VBUILD_PUBKEY }}
      - name: Build packages
        run: make package-${{ matrix.arch }}
        env:
          VBUILD_KEY_NAME: oxide
        timeout-minutes: 15
      - name: Save packages
        uses: actions/upload-artifact@v7
        with:
          name: vellum-${{ matrix.arch }}
          path: release/${{ matrix.arch }}/
      - name: Save build
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ matrix.arch }}
          path: .build/package/src/release/
          include-hidden-files: true

  repo:
    name: Update repo
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
    environment: apk.eeems.codes
    if: github.repository == 'Eeems-org/oxide' && github.ref == 'refs/heads/master'
    strategy:
      matrix:
        arch:
          - armv7
          - aarch64
      fail-fast: false
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v6
      - name: Download executables
        id: download
        uses: actions/download-artifact@v8
        with:
          pattern: vellum-${{ matrix.arch }}
          merge-multiple: true
          path: release/${{ matrix.arch }}/
      - name: Generate index
        run: |
          set -e
          mkdir -p keys
          touch keys/oxide.rsa
          chmod 600 keys/oxide.rsa
          echo "$privkey" > keys/oxide.rsa
          openssl rsa -in keys/oxide.rsa -pubout -out keys/oxide.rsa.pub
          docker run --rm \
            -v "$PWD/release/$arch:/packages:Z" \
            -v "$PWD/keys:/keys:ro" \
            -w /packages \
            ghcr.io/eeems/vbuild-builder:main \
            sh -ec "
              cp /keys/oxide.rsa* /etc/apk/keys/
              apk index --output=APKINDEX.tar.gz *.apk
              abuild-sign -k /keys/oxide.rsa APKINDEX.tar.gz
              chown $(id -u):$(id -g) APKINDEX.tar.gz
            "
            cp keys/oxide.rsa.pub release/$arch/
        env:
          privkey: ${{ secrets.VBUILD_PRIVKEY }}
          arch: ${{ matrix.arch }}
      - name: Rsync
        run: |
          set -e
          mkdir -p tmp
          touch tmp/server_key
          chmod 600 tmp/server_key
          echo "$ssh_key" > tmp/server_key
          ssh="ssh $ssh_args -oStrictHostKeyChecking=no -i tmp/server_key"
          rsync -Pcuav --delete -e "$ssh" \
            release/$arch/ \
            "$ssh_user@$ssh_server:$ssh_path/staging/$arch"
          $ssh \
            "$ssh_user@$ssh_server" \
            "rsync -a --delete --link-dest='$ssh_path/staging/$arch' '$ssh_path/staging/$arch/.' '$ssh_path/live/$arch'"
          rm tmp/server_key
        env:
          ssh_user: ${{ vars.SSH_USER }}
          ssh_server: ${{ vars.SSH_SERVER }}
          ssh_path: ${{ vars.SSH_PATH }}
          ssh_key: ${{ secrets.SSH_KEY }}
          ssh_args: ${{ vars.SSH_ARGS }}
          arch: ${{ matrix.arch }}
