name: Build with Nix

on: [push, pull_request]

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v14
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: nix-remarkable
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build package
      run: nix-build --argstr system 'x86_64-linux'
      timeout-minutes: 15
    - name: Build packages
      run: |
        mkdir output
        find -L result -name '*.ipk' | while read -r file; do
          cp "$file" output/"$(basename $file)"
        done
    - name: Save packages
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: output
