name: Build with Nix

on:
  push:
    branches:
      - master
    paths:
      - 'applications/**'
      - 'shared/**'
      - 'assets/**'
      - 'interfaces/**'
      - 'Makefile'
      - '*.nix'
  pull_request:
    paths:
      - 'applications/**'
      - 'shared/**'
      - 'assets/**'
      - 'interfaces/**'
      - 'Makefile'
      - '*.nix'
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: nix-remarkable
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build package
      run: nix-build --argstr system 'x86_64-linux'
      timeout-minutes: 15
    - name: Build packages
      run: |
        mkdir output
        find -L result -name '*.ipk' | while read -r file; do
          cp "$file" output/"$(basename $file)"
        done
    - name: Save packages
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: output
